[Chained] Remove unnecessary names
infrared-dao/infrared-default-list pull request #51
Opened 2024-12-28 19:50 UTC by mlenser

@multibear-infra we don't use the name of the tokens and will only ever use the symbols. For gauges the name should be based on the symbols of the underlying tokens.

2025-01-01 11:22 UTC, multibear-infra approved these changes
Looks good to me
Just a few questions about the names and cases when we might still want the partner defined name to be there...

2025-01-01 11:22 UTC, multibear-infra commented on src/gauges/bartio.json
I assume you are removing these names from the gauges because we decided to use the underlying token names to automatically generate the standard gauge names for LP tokens... we might still want them in the case that the name for the token onchain is terrible and unusable -- examples in the past being that it was UTF-8 weird characters and unreadable, or if it would create a conflict with another existing name.

The logic now is to autoname based on the underlying token names unless there is one of these known problems in which case we can fall back to the user given name.

One other issue is lots of pools actually use WBERA instead of BERA but want the pool name to say BERA (and similar for other wrapped tokens).  This name field was previously giving that power to the partner to determine how to best show the pool.

2025-01-01 11:22 UTC, multibear-infra commented on src/tokens/bartio.json
You no longer want these human readable names for the tokens?  We should just use the onchain name() call?  This is still different from the symbol() but in practice lots of tokens have the same name() and symbol() and almost none of them have these nice multi-word names onchain

2025-01-01 15:03 UTC, mlenser commented on src/gauges/bartio.json
> One other issue is lots of pools actually use WBERA instead of BERA but want the pool name to say BERA (and similar for other wrapped tokens)

Ya, that's incorrect. The pool should match the tokens. I just fixed one of these cases the other day. It's a perfect example of why we should rely on the underlying tokens only.

> This name field was previously giving that power to the partner to determine how to best show the pool.

We don't want partners to choose. We want uniformity based on the underlying tokens.

2025-01-01 15:07 UTC, mlenser commented on src/tokens/bartio.json
We never use name - only symbol. So no need to provide a name for tokens.

2025-01-02 13:09 UTC, multibear-infra commented on src/gauges/bartio.json
Ok gotcha and agree on those points then.  
What about when the onchain name or token symbol is actually illegible with weird characters, or would be conflicting with other names?

Conflicts can occur in two different ways --> LP tokens from different partners use the same underlying tokens like imagine BEX and Kodiak each had their own BERA-HONEY pools.  This is why we had been appending the protocol id to the front of the generated symbol.

The other way is if the partner was stupid in setting up their tokens, so one example was the sweep-n-flip tokens, instead of naming their pools something sensible all of their pools have the same name as "SweepnFlip LP".  Even if we generate the names from the underlying tokens the same problem is possible, they could name their underlying base tokens with a conflicting name.

So if we always want to generate the symbol we at least need a way to automatically detect and adapt if there is a conflct...

2025-01-02 13:11 UTC, multibear-infra commented on src/tokens/bartio.json
Ok, good to know, we will need to update the API then as well because we previously thought all tokens had to have a name.  This is true of both LP tokens used in gauge staking and the base tokens like BERA. HONEY, iBGT that we only need symbol?

2025-01-02 14:21 UTC, kuma-ir requested changes
names should be left alone please .. we want them for human legibility, also the PR reviewer can do same basic sanity checks on them i.e there's something to fall back on.

2025-01-02 14:21 UTC, kuma-ir commented on README.md
> -     "name": "Your Gauge Name",
please leave all names in here .. even if we don't serve them .. for human legibility reason we want names in here.

2025-01-02 14:21 UTC, kuma-ir commented on README.md
> -     "name": "Your Token Name",
please leave all names in here .. even if we don't serve them .. for human legibility reason we want names in here.

2025-01-02 14:21 UTC, kuma-ir commented on schema/gauge-list-schema.json
> -          "name",
please leave all names in here .. even if we don't serve them .. for human legibility reason we want names in here.

2025-01-02 14:21 UTC, kuma-ir commented on schema/token-list-schema.json
> -          "name": { "type": "string" },
please leave all names in here .. even if we don't serve them .. for human legibility reason we want names in here.

2025-01-02 16:29 UTC, mlenser commented on src/tokens/bartio.json
All tokens probably do have to have a name. It's not relevant for our app at this time.

If it becomes relevant for our app then the names should come from on-chain. Uniswap uses the names in their token selector for example: 
![image](https://github.com/user-attachments/assets/ecdc178b-82ef-46a2-a170-2d8dfe588033)

2025-01-02 16:30 UTC, mlenser commented on README.md
> -     "name": "Your Gauge Name",
> the PR reviewer can do same basic sanity checks on them i.e there's something to fall back on.

We haven't and we won't. We had at least 1 token with an incorrect name and another PR also has an incorrect name. We have the actual data (on chain). We should not rely on data entry which is error prone.

2025-01-02 20:43 UTC, mlenser commented on README.md
> -     "name": "Your Gauge Name",
https://github.com/infrared-dao/infrared-default-list/pull/58

2025-01-03 05:02 UTC, kuma-ir approved these changes
okay .. fair enough .. let's keep
- names for gauges
- symbols for tolens

2025-01-06 11:05 UTC, merged